### ISSUE TITLE
Use p6 version of quick_wdm_2_txt_hour_2_hour

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/cbp6#33]
Update all code to use this version of quick_wdm:
```/opt/model/p6-devel/p6-4.2018/code/bin/quick_wdm_2_txt_hour_2_hour```

See related pull request #32

**Comment by hdaniel7** [comment]
We tested the new quick_wdm_2_txt_hour_2_hour and successfully generated a 1984-2014 .csv for a river segment in phase 6 scenario CFBASE30Y20180615. We'll re-generate .csvs for scenario CFBASE30Y20180615 for river segments of interest and use this updated script to generate .csv files in the future.

**Comment by rburghol** [comment]
Thanks Daniel that is fantastic.  For outputs, on the deq2, use this dir: /opt/model/p6/p6_gb604

Your functionalization of the code looks good: maybe we should just add that to the R directory like you did the other functions so that it becomes a Roxygenized part of the package?

**Comment by hdaniel7** [comment]
We are generating them on deq2, we've just been generating them in the same directory as the .wdm files (http://deq2.bse.vt.edu/p6/p6_gb604/tmp/wdm/river/CFBASE30Y20180615/stream/) since .csv files from different scenarios would have the same name and overwrite each other if we stored them in the overall /opt/model/p6/p6_gb604 directory.

Are you talking about the functionalization of the land_use_eos_all script, or which functionalized code are you talking about?

**Comment by hdaniel7** [comment]
For future reference: a short tutorial of how to generate .csv files from phase 6 data has been created [here](https://drive.google.com/open?id=1O8mpSpBxXlcvN21_siD7Sl4DOn-pBYyRk7NAEzDaQ40), using information copied and slightly modified from the old phase 5 "step2-begin_modeling_and_landuse_docs.docx" document

**Comment by rburghol** [comment]
Good thinking -- putting them in the same directory of the WDM will help us keep those scenarios straight - thanks!

And yes, functionalize land_use_eos_all (), that is, it should be exposed as part of the cbp6 package -- unless you were thinking otherwise?

**Comment by hdaniel7** [comment]
Land_use_eos_all.R has been functionalized and is detailed a bit more [here](https://github.com/HARPgroup/cbp6/issues/26#issuecomment-504026305).  I can move it so that it will be included within the cbp6 package, although I'm not sure if it would be of any use to the common user -- downsides are that it requires the pulling of data from deq2.bse.vt.edu and only completes one step (the compilation of already generated land use files) which is not particularly useful unless the land use inputs are being analyzed.  Thoughts on whether it should be included?

**Comment by rburghol** [comment]
Let's add the WDM data path variable "wdmpath" to thje functions input parameters.  That way, deq2 http isn't hard-coded in there.  Essentially, it then becomes usable by *anyone* with WDM files.  And also, by us in a more flexible fashion.  For that matter, it is very ineffecient to use the http: request to get those files when we are operating from the same server.  That was necessary when analysts are developing on their desktops, but as soon as we run the code from the server, we don't need http.  It would be more efficient for us to use something like "wdmpath = '/opt/model/p6/p6_gb604/' " as an input parameter, then the web server would not be involved at all.

**Comment by hdaniel7** [comment]
Fn_land_use_eos_all.R has been updated, replacing the "mod.phase" variable with the "wdmpath" variable. If "/opt/model/p6/p6_gb604" is inputted as wdmpath, the function uses the data stored on the deq2 server.  It has been tested on deq2.

**Comment by rburghol** [comment]
Awesome!
