### ISSUE TITLE
Need to obtain data for Potomac (and maybe other) areas outside VA

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/cbp6#6]
Initial QA of current model data suggests that we received Virginia only.

**Comment by rburghol** [comment]
Reported issue to CBP crew, requested data by major basin codes as follows:
- R - Rappahannock
- J - James
- Y - York
- E - Eastern Shore
- W - Western Shore
- P - Potomac

**Comment by rburghol** [comment]
This data is on the way as of 12noon on 6/12/2019.  Potomac should be ready soon.  Let me know when you all verify it.

**Comment by hdaniel7** [comment]
As of 9AM on 6/13/2019, there is no data on PU3_4450_4440, the Jennings Randolph segment outside of VA.  There is data on Potomac segments within VA -- this data has been available since the start of our access to phase 6 data.  I'll check again in the coming days and inform you when data for PU3_4450_4440 (implying other outside VA Potomac segs as well) is available.

**Comment by rburghol** [comment]
Thanks for the check-in -- that's cause I forgot to run the job before I left last night!  It is copying now...

**Comment by rburghol** [comment]
The sync for data appears complete.  Please check and let me know at your earliest convenience.

**Comment by kevindandrea** [comment]
It looks as if the sync for the data has been completed. I was able to locate the wdm file for Jennings Randolph (WV) and access climate change scenario data.

**Comment by rburghol** [comment]
Awesome -- Thanks! Marking this closed.
